name: My First Workflow

on: push

jobs:
    firs_job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Read Files
              run: |
                echo "Welcome step"
                ls -la
                cat README.md
            
            - name: Generate ASCII Artworks
              run: cowsay -f dragon "Run for cover. I am a DRAGON ... RAWR" >> dragon.txt