name: Generate ASCII Artwork Workflow

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Clone the repo
              uses:  actions/checkout@v4
            
            - name: List files
              run: ls -ltra

            - name: Execute Generate ASCII Artwork Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

            